//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_CouchPotato : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean ResetPosition
        {
            get
            {
                return SteamVR_Actions.couchPotato_ResetPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean CalibrateLeaning
        {
            get
            {
                return SteamVR_Actions.couchPotato_CalibrateLeaning;
            }
        }
        
        public virtual SteamVR_Action_Boolean Break
        {
            get
            {
                return SteamVR_Actions.couchPotato_Break;
            }
        }
        
        public virtual SteamVR_Action_Vector2 dash
        {
            get
            {
                return SteamVR_Actions.couchPotato_dash;
            }
        }
    }
}
