//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_MySet : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Click
        {
            get
            {
                return SteamVR_Actions.mySet_Click;
            }
        }
        
        public virtual SteamVR_Action_Pose RightPose
        {
            get
            {
                return SteamVR_Actions.mySet_RightPose;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Throttle
        {
            get
            {
                return SteamVR_Actions.mySet_Throttle;
            }
        }
        
        public virtual SteamVR_Action_Boolean ResetPosition
        {
            get
            {
                return SteamVR_Actions.mySet_ResetPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean CalibrateLeaning
        {
            get
            {
                return SteamVR_Actions.mySet_CalibrateLeaning;
            }
        }
        
        public virtual SteamVR_Action_Boolean Break
        {
            get
            {
                return SteamVR_Actions.mySet_Break;
            }
        }
    }
}
